# This workflow will do a clean install of node dependencies, then run tests that have been created for the backend code

name: Backend Tests
on:
  pull_request:
  pull_request_target:
jobs:
  backendTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./backend
      run: npm ci
    - name: Run backend tests
      working-directory: ./backend
      run: npm run test
